### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tab58** [rreusser/summation-algorithms#2]
I see on the README that the licensing is pending confirmation. To spark the discussion and document it, I'm fine with licensing my bit of code as MIT.

**Comment by rreusser** [comment]
Yeah, your gist was great. Just wanted to organize and benchmark carefully, which meant a repo. Ultimately, I'd like to use this as a basis for something similar to what cwise does and basically plug a more general map-reduce operation into this template (via code-rewriting instead of function calls). And I hate to throw repos online without _some_ sort of license. I'm fine with anything, just didn't want to speak for you. 👍
